apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: team-a
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/tiffanny29631/anthos-config-management-samples
    branch: ns-selector
    dir: pp-unstructured/team-a
    auth: none
