apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: team-a
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/tiffanny29631/csp-config-management
    branch: ns-repo
    dir: pp-unstructured/team-a
    auth: none
