apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: config-sync-hpa
  namespace: config-management-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: root-reconciler-rs-quickstart
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pod
    external:
      metric:
        name: declared_resources
        selector: {}
      target:
        type: Value
        value: 100  # Adjust this value based on your scaling requirements and metric units

