apiVersion: v1
kind: Pod
metadata:
  namespace: dependsontest
  name: pod1
  annotations:
    config.kubernetes.io/depends-on: /namespaces/dependsontest/Pod/pod0
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
