apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-cli-service # kpt-set: ${app-name}
  namespace: gamestore
  labels:
    app: wp-cli-service # kpt-set: ${app-name}
spec:
  replicas: 2 # kpt-set: ${replicas}
  selector:
    matchLabels:
      app: wp-cli-service # kpt-set: ${app-name}
  template:
    metadata:
      labels:
        app: wp-cli-service # kpt-set: ${app-name}
    spec:
      securityContext:
        # All containers must run as a non-root user; we choose 10101 as
        # a uid/gid that is unlikely to conflict with any container.
        runAsNonRoot: true
        runAsUser: 10101
        runAsGroup: 10101
        # An unset fsGroup indicates that the ownership of files in
        #   mounted volumes will not be modified at mount time.
        # fsGroup:
      # Don't use host network, PID, or IPC namespaces
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - name: cloudsql-proxy
        image: "gcr.io/cloudsql-docker/gce-proxy:1.21.0" # kpt-set: gcr.io/cloudsql-docker/gce-proxy:${proxy-image-version}
        command:
        - "/cloud_sql_proxy"
        - "-instances=wpe-wp-cli-service-dev:us-east1:wp-cli-service=tcp:5432" # kpt-set: -instances=${app-project}:${db-region}:${db-instance}=tcp:5432
        - "-ip_address_types=PRIVATE"
        - "-structured_logs=true"
        - "-verbose=false"
        securityContext:
          # The container must run as a non-root user; we choose 10101 as
          # a uid/gid that is unlikely to conflict with any container.
          runAsNonRoot: true
          runAsUser: 10101
          runAsGroup: 10101
          # An unset fsGroup indicates that the ownership of files in
          #   mounted volumes will not be modified at mount time.
          # fsGroup:
          # Containers may not run in privileged mode
          privileged: false
          allowPrivilegeEscalation: false
          # Containers cannot write to the root FS
          readOnlyRootFilesystem: true
          # Containers do not mount the sensitive subdirectories of /proc
          procMount: "DefaultProcMount"
          # Containers must not add any capabilities, and they must drop NET_RAW and SYS_ADMIN
          capabilities:
            add: []
            drop: [NET_RAW, SYS_ADMIN]
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 200m
            memory: 512M
      affinity:
        podAntiAffinity:
          # instances should run in different zones
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: wp-cli-service # kpt-set: ${app-name}
              topologyKey: topology.kubernetes.io/zone
            weight: 100

