apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: wp-cli-service
      name: wp-cli-service
      namespace: gamestore
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: wp-cli-service
      template:
        metadata:
          labels:
            app: wp-cli-service
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: wp-cli-service
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
          containers:
          - command:
              "/cloud_sql_proxy",
              "-instances=wpe-wp-cli-service-dev:us-east1:wp-cli-service=tcp:5432",
              "-ip_address_types=PRIVATE",
              "-structured_logs=true",
              "-verbose=false"
            - wpe-wp-cli-service-dev:us-east1:wp-cli-service
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:1.12.0
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: "/liveness"
                port: 7070
              initialDelaySeconds: 0
              periodSeconds: 60
              timeoutSeconds: 30
            name: cloudsql-proxy
            resources:
              limits:
                cpu: 500m
                memory: 1G
              requests:
                cpu: 200m
                memory: 512M
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add: []
                drop:
                - NET_RAW
                - SYS_ADMIN
              privileged: false
              procMount: DefaultProcMount
              readOnlyRootFilesystem: true
              runAsGroup: 10101
              runAsNonRoot: true
              runAsUser: 10101
            startupProbe:
              failureThreshold: 20
              httpGet:
                path: "/startup"
                port: 7070
              periodSeconds: 1
              timeoutSeconds: 5
          hostIPC: false
          hostNetwork: false
          hostPID: false
          securityContext:
            runAsGroup: 10101
            runAsNonRoot: true
            runAsUser: 10101
          serviceAccountName: wp-cli-service
